# Generated by Django 3.1.7 on 2021-03-30 01:18

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('alteracao', models.DateTimeField(auto_now=True, verbose_name='Alteração')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('idade', models.IntegerField(verbose_name='Idade')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Peso')),
                ('genero', models.CharField(choices=[('m', 'Masculino'), ('f', 'Feminino'), ('o', 'Outro')], max_length=9, verbose_name='Gênero')),
                ('foto', models.ImageField(upload_to=core.models.get_auto_path, verbose_name='Foto')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
