# Generated by Django 3.1.7 on 2021-03-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='mostrar',
            field=models.BooleanField(default=True, verbose_name='Mostrar?'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='genero',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('outro', 'Outro')], max_length=9, verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso'),
        ),
    ]
